version: '3.4'

services:
  sourcegraph2api:
    image: deanxv/sourcegraph2api:latest
    container_name: sourcegraph2api
    restart: always
    ports:
      - "7033:7033"
    volumes:
      - ./data:/app/sourcegraph2api/data
    environment:
      - SG_COOKIE=******  # cookie (多个请以,分隔)
      - API_SECRET=123456  # [可选]接口密钥-修改此行为请求头校验的值(多个请以,分隔)
      - TZ=Asia/Shanghai